# Generated by Django 4.0 on 2022-01-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
